#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: restaurant-service
#          uri: lb://RESTAURANT-SERVICE
#          predicates:
#            - Path=/restaurant/**
#          filters:
#            - AuthenticationFilter
#
#        - id: security-service
#          uri: lb://SECURITY-SERVICE
#          predicates:
#            - Path=/auth/**
#
#  application:
#    name: API-GATEWAY
#
#eureka:
#  client:
#    service-url:
#      defaultZone : http://localhost:8761/eureka/